export const Img = {
  UserDefaultImg: "/userDefault.png",
  RightArrowImg: "/rightArrow.png",
  VolumeImg: "/Volume.png",
  UserGroupImg: "/userGroup.png",
  ShareImg: "/share.png",
  PlayImg: "/play.png",
  ArbitrumLogo: "/arbitrum-logo.png",
  HomeImg: "/Home.png",
  RoulletImg: "/roullet.png",
  WalletImg: "/Wallet.png",
  SettingImg: "/Settings.png",
  ArrowImg: "/Arrow.svg",
  LogoImg: "/Conet.svg",
  CopyImg: "/Copy.svg",
};
