export const Img = {
  UserDefaultImg: "/userDefault.png",
  RightArrowImg: "/rightArrow.png",
  VolumeImg: "/Volume.png",
  UserGroupImg: "/userGroup.png",
  ShareImg: "/share.png",
  PlayImg: "/play.png",
  ArbitrumLogo: "/arbitrum-logo.png",
  HomeImg: "/Home.png",
  ActiveHomeImg: "/activeHome.png",
  RoulletImg: "/roullet.png",
  WalletImg: "/Wallet.png",
  SettingImg: "/Settings.png",
  BlueLeftArrow: "/blueLeftArrow.png",
  PinkLeftArrow: "/pinkLeftArrow.png",
  LeadLeftArrow: "/leftArrow.png",
  LeadRightArrow: "/leadRightArrow.png",
  AllImg: "/allLead.png",
  MonthlyImg: "/monthLead.png",
  WeeklyImg: "/weeklyLead.png",
  DailyImg: "/dayLead.png",
  LeadUserDefault: "/leadUserDefault.png",
  FirstLeadBadgeImg: "/first.png",
  SecondLeadBadgeImg: "/second.png",
  ThirdLeadBadgeImg: "/third.png",
  BioDefaultImg: "/bioDefaultImg.png",
};
