export const SkinImg = {
  Fssuit: "/skinStore/astronaut_main.png",
  Shibnet: "/skinStore/doge 1.png",
  Grmpnet: "/skinStore/grumpy.png",
  Cofrog: "/skinStore/pepefrog.png",
  Johnnyet: "/skinStore/shining.png",
  Cowave: "/skinStore/The Great Wave Kanagawa.png",
  Netarry: "/skinStore/The Night Starry.png",
  Cofry: "/skinStore/Squinting Fry.png",
  Facenet: "/skinStore/facepalm.png",
  Cocpz: "/skinStore/Changpeng Zhao.png",
  Cotalik: "/skinStore/vitalik.png",
  Emco: "/skinStore/elon.png",
  Tconet: "/skinStore/terminator.png",
  Conetrix: "/skinStore/matrix.png",
  Corvin: "/skinStore/The hitchhiker's guide to the galaxy.png",
  Covdr: "/skinStore/starwars.png",
  Vulconet: "/skinStore/startrek_2.png",
  Netwid: "/skinStore/batman.png",
  Spmanet: "/skinStore/spiderman.png",
  Wwnet: "/skinStore/wonderwoman.png",
  Batnet: "/skinStore/blackwidow.png",
  Rewards: "/skinStore/rewards.png",
};
