import { SkinImg } from "./skinStoreImage";

export const Skins = [
  {
    key: 1,
    Img: SkinImg.Fssuit,
    status: "used",
    title: "FS Suit",
    desc: "Your first suit to start your CoNETian mission.",
    price: 0,
  },
  {
    key: 2,
    Img: SkinImg.Shibnet,
    status: "buy",
    title: "ShibNET",
    desc: "Much wow, very epic—dominate in style with the iconic ShibNET skin.",
    price: 2,
  },
  {
    key: 3,
    Img: SkinImg.Grmpnet,
    status: "buy",
    title: "GrmpNET",
    desc: "Unleash your inner grump with the iconic, no-nonsense GrmpNET skin.",
    price: 2,
  },
  {
    key: 4,
    Img: SkinImg.Cofrog,
    status: "buy",
    title: "CoFROG",
    desc: "Fly through all the feels with the CoFROG skin—perfect for every mood.",
    price: 2,
  },
  {
    key: 5,
    Img: SkinImg.Johnnyet,
    status: "buy",
    title: "JohnNyET",
    desc: "Break through the game with the chilling JohnNyET skin—embrace the iconic madness.",
    price: 2,
  },
  {
    key: 6,
    Img: SkinImg.Cowave,
    status: "buy",
    title: "CoWave",
    desc: "Ride the waves of power with the CoWave skin—where classic art meets epic gameplay.",
    price: 5,
  },
  {
    key: 7,
    Img: SkinImg.Netarry,
    status: "buy",
    title: "NETarry",
    desc: "Illuminate the battlefield with the NETarry skin—bring VanG masterpiece to life.",
    price: 5,
  },
  {
    key: 8,
    Img: SkinImg.Cofry,
    status: "buy",
    title: "CoFRY",
    desc: "Stay skeptical and stylish with the CoFry skin—because things just don’t add up.",
    price: 5,
  },
  {
    key: 9,
    Img: SkinImg.Facenet,
    status: "buy",
    title: "FaceNET",
    desc: "Master frustration in style with the ultimate FaceNET skin—because some moments need no words.",
    price: 5,
  },
  {
    key: 10,
    Img: SkinImg.Cocpz,
    status: "buy",
    title: "CoCPZ",
    desc: "Channel the power of Web3 with the CoCPZ skin—innovative and unstoppable.",
    price: 10,
  },
  {
    key: 11,
    Img: SkinImg.Cotalik,
    status: "buy",
    title: "CoTalik",
    desc: "Embrace blockchain brilliance with the CoTalik skin—where innovation meets gameplay.",
    price: 10,
  },
  {
    key: 12,
    Img: SkinImg.Emco,
    status: "buy",
    title: "EMCo",
    desc: "Blast off with the EMCo skin—where visionary style meets out-of-this-world gameplay.",
    price: 10,
  },
  {
    key: 13,
    Img: SkinImg.Tconet,
    status: "buy",
    title: "T-CoNET",
    desc: "Dominate with the relentless T-CoNET skin—channeling unstoppable power from the future.",
    price: 10,
  },
  {
    key: 14,
    Img: SkinImg.Conetrix,
    status: "buy",
    title: "CoNETrix",
    desc: "Enter the digital realm with the CoNETrix skin—unlock your true potential and bend reality.",
    price: 20,
  },
  {
    key: 15,
    Img: SkinImg.Corvin,
    status: "buy",
    title: "CoRVIN",
    desc: "Embrace existential ennui with the CoRVIN skin—your stylishly pessimistic guide through the galaxy.",
    price: 20,
  },
  {
    key: 16,
    Img: SkinImg.Covdr,
    status: "buy",
    title: "CoVDR",
    desc: "Rule the galaxy with the CoVDR skin—unleash dark power and iconic presence.",
    price: 20,
  },
  {
    key: 17,
    Img: SkinImg.Vulconet,
    status: "buy",
    title: "VulCoNET",
    desc: "Channel logical prowess with the VulCONET skin—embrace calm, cool, and interstellar precision.",
    price: 20,
  },
  {
    key: 18,
    Img: SkinImg.Netwid,
    status: "buy",
    title: "NETwid",
    desc: "Strike with stealth and agility in the NETwid skin—where espionage meets epic action.",
    price: 50,
  },
  {
    key: 19,
    Img: SkinImg.Spmanet,
    status: "buy",
    title: "SPMaNET",
    desc: "Swing into action with the SPMaNET skin—bringing web-slinging heroics to the battlefield.",
    price: 50,
  },
  {
    key: 20,
    Img: SkinImg.Spmanet,
    status: "buy",
    title: "wwNET",
    desc: "Embody strength and grace with the wwNET skin—defend justice with legendary power.",
    price: 50,
  },
  {
    key: 21,
    Img: SkinImg.Batnet,
    status: "buy",
    title: "BatNET",
    desc: "Step into the shadows with the BatNET skin—strike fear into the hearts and fight for justice.",
    price: 50,
  },
];
