export const SkinImg = {
  Fssuit: "/skin store/astronaut_main.png",
  Shibnet: "/skin store/doge 1.png",
  Grmpnet: "/skin store/grumpy.png",
  Cofrog: "/skin store/pepefrog.png",
  Johnnyet: "/skin store/shining.png",
  Cowave: "/skin store/The Great Wave Kanagawa.png",
  Netarry: "/skin store/The Night Starry.png",
  Cofry: "/skin store/Squinting Fry.png",
  Facenet: "/skin store/facepalm.png",
  Cocpz: "/skin store/Changpeng Zhao.png",
  Cotalik: "/skin store/vitalik.png",
  Emco: "/skin store/elon.png",
  Tconet: "/skin store/terminator.png",
  Conetrix: "/skin store/matrix.png",
  Corvin: "/skin store/The hitchhiker's guide to the galaxy.png",
  Covdr: "/skin store/starwars.png",
  Vulconet: "/skin store/startrek_2.png",
  Netwid: "/skin store/batman.png",
  Spmanet: "/skin store/spiderman.png",
  Wwnet: "/skin store/wonderwoman.png",
  Batnet: "/skin store/blackwidow.png",
  Rewards: "/skin store/rewards.png",
};
